#!/usr/bin/perl

use warnings;
use strict;

die "program x y density" unless (scalar(@ARGV) == 7);

my ($x, $y, $density, $empty, $obs, $full, $name) = @ARGV;

open(my $fh, '>', $name) or die "Cannot open map file: $!";

print $fh "$y$empty$obs$full\n";
for (my $i = 0; $i < $y; $i++) {
	for (my $j = 0; $j < $x; $j++) {
		if (int(rand($y) * 2) < $density) {
			print $fh "$obs";
		}
		else {
			print $fh "$empty";
		}
	}
	print $fh "\n";
}
close ($fh);
